CREATE TABLE REGISTROS(
  ID INT NOT NULL AUTO_INCREMENT,
  IP VARCHAR(300),
  PUERTO INT NOT NULL,
  PROTOCOLO VARCHAR(300),
  SERVICIO VARCHAR(300),
  FECHA VARCHAR(300),
  CONSTRAINT PK_REGISTROS PRIMARY KEY(ID)
);

